server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      okta:
#        client-id: your-app-client-id
#        client-secret: your-app-client-secret
#        authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
#        token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
#        user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
        jwk-set-uri: https://dev-259824.oktapreview.com/oauth2/ausar5cbq5TRRsbcJ0h7/v1/keys
